### ISSUE TITLE
Can't compile on ubuntu

### ISSUE THREAD

**Issue by emdio** [zxqfl/sashimi#2]
I tried to compile sashimi with cargo 1.30.0, but got errors:

$ cargo build --release --all
    Updating crates.io index
 Downloading smallvec v0.6.1                                                    
 Downloading memmap v0.6.2                                                      
 Downloading simplelog v0.5.1                                                   
 Downloading shakmaty v0.5.1                                                    
 Downloading argparse v0.2.1                                                    
 Downloading pgn-reader v0.4.0                                                  
 Downloading slurp v1.0.1                                                       
 Downloading chess v0.4.2                                                       
 Downloading num_cpus v1.8.0                                                    
 Downloading rand v0.4.2                                                        
 Downloading madvise v0.1.0                                                     
 Downloading log v0.4.1                                                         
 Downloading float-ord v0.2.0                                                   
 Downloading libc v0.2.40                                                       
 Downloading term v0.5.1                                                        
 Downloading chrono v0.4.2                                                      
 Downloading byteorder v1.2.2                                                   
 Downloading cfg-if v0.1.3                                                      
 Downloading num-integer v0.1.36                                                
 Downloading time v0.1.39                                                       
 Downloading num-traits v0.2.2                                                  
 Downloading btoi v0.1.3                                                        
 Downloading bitflags v1.0.3                                                    
 Downloading option-filter v1.0.1                                               
 Downloading arrayvec v0.4.7                                                    
 Downloading nodrop v0.1.12                                                     
 Downloading version_check v0.1.3                                               
 Downloading memchr v2.0.1                                                      
 Downloading rand v0.3.22                                                       
 Downloading crossbeam v0.3.2                                                   
 Downloading pod v0.5.0                                                         
 Downloading packed v0.4.2                                                      
 Downloading read_exact v0.0.1                                                  
 Downloading uninitialized v0.0.2                                               
   Compiling uninitialized v0.0.2                                               
   Compiling libc v0.2.40                                                       
   Compiling version_check v0.1.3                                               
   Compiling read_exact v0.0.1                                                  
   Compiling packed v0.4.2                                                      
   Compiling nodrop v0.1.12                                                     
   Compiling num-traits v0.2.2                                                  
   Compiling cfg-if v0.1.3                                                      
   Compiling byteorder v1.2.2                                                   
   Compiling slurp v1.0.1                                                       
   Compiling option-filter v1.0.1                                               
   Compiling bitflags v1.0.3                                                    
   Compiling crossbeam v0.3.2                                                   
   Compiling smallvec v0.6.1                                                    
   Compiling float-ord v0.2.0                                                   
   Compiling argparse v0.2.1                                                    
   Compiling arrayvec v0.4.7                                                    
   Compiling log v0.4.1                                                         
   Compiling rand v0.4.2                                                        
   Compiling memmap v0.6.2                                                      
   Compiling time v0.1.39                                                       
   Compiling memchr v2.0.1                                                      
   Compiling num_cpus v1.8.0                                                    
   Compiling madvise v0.1.0                                                     
   Compiling term v0.5.1                                                        
   Compiling shakmaty v0.5.1                                                    
   Compiling sashimi v0.2.0 (/home/emilio/soft/git/sashimi/engine)              
   Compiling btoi v0.1.3                                                        
   Compiling num-integer v0.1.36                                                
   Compiling rand v0.3.22                                                       
   Compiling pod v0.5.0                                                         
   Compiling chrono v0.4.2                                                      
   Compiling chess v0.4.2                                                       
   Compiling arena v0.1.0 (/home/emilio/soft/git/sashimi/arena)                 
   Compiling mcts v0.2.0 (/home/emilio/soft/git/sashimi/mcts)                   
error[E0554]: #![feature] may not be used on the stable release channel         
 --> mcts/src/lib.rs:1:1                                                        
  |                                                                             
1 | #![feature(integer_atomics)]                                                
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                
                                                                                
error: aborting due to previous error                                           
                                                                                
For more information about this error, try `rustc --explain E0554`.             
error: Could not compile `mcts`.                                                
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by zxqfl** [comment]
You need to use the nightly release of Rust. If you installed with rustup you can run the following commands to do so:
```
rustup install nightly
rustup default nightly
```
